# Roadrunners
language: python
python:
    - "2.7"
addons:
    postgresql: 9.3
before_install:
    - sudo apt-get update
    - sudo apt-get install texlive-full
    - sudo apt-get install xsltproc
    - sudo apt-get install python-imaging
    # lxml
    - sudo apt-get install zlib1g-dev libxml2-dev libxslt1-dev
    - pip install lxml
    # Install pybit
    - git clone https://github.com/nicholasdavidson/pybit.git
    - cd pybit && python setup.py develop && cd ..
    # Install coyote
    - git clone https://github.com/Connexions/coyote.git
    - cd coyote && python setup.py develop && cd ..
    # Clone printing
    - git clone https://github.com/Rhaptos/Products.RhaptosPrint.git
    # Clone oer.exports and cnx-buildout
    # - git clone https://github.com/Connexions/oer.exports.git
    - git clone https://github.com/Rhaptos/cnx-buildout.git
    # get and install prince pdf generator
    - wget http://www.princexml.com/download/prince_9.0-5_ubuntu12.04_amd64.deb
    - sudo dpkg -i prince_9.0-5_ubuntu12.04_amd64.deb
    # Install coverage
    - pip install coverage
    - pip install coveralls
install:
    - python setup.py develop
script:
    - coverage run --source=roadrunners setup.py test
after_success:
    # Report test coverage
    - coveralls
notifications:
    email: false    